<?php

/**
 * @file
 * Contains no_views_php.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function no_views_php_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the no_views_php module.
    case 'help.page.no_views_php':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom views field to include PHP logic in views.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function no_views_php_theme() {
  return [
    'no_views_php' => [
      'render element' => 'children',
    ],
  ];
}
